source 'https://cdn.cocoapods.org/'

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'OpenKuiklyIOSRender' , '~> 2.7.0'
  pod 'shared', :path => '../shared'

  pod 'SDWebImage'
  # MMKV Module（独立原生模块，MMKV 依赖由 podspec 传递引入）
  pod 'KuiklyMMKVIOS', :path => '../KuiklyMMKVIOS'
end